### ISSUE TITLE
Shield cast bar not working

### ISSUE THREAD

**Issue by Wolfeg** [trincasidra/trincaui#3]
Target castbar doesn't change color if it isn't interruptible. First i've found typo at https://github.com/trincasidra/trincaui/blob/795301e9a547f6f6511d36917371e30b64c4e441/core/functions.lua#L452-L458 (`colorss` instead of `colors`) but it doesn't help. I'm not so good at wow lua scripting, so my attempts to fix it has been failed. I hope you'll fix it.

**Comment by trincasidra** [comment]
Actually never realized this, great catch! Indeed, fixing the typo is not enough since it looks like the Cast Shield from oUF is used selectively.

You can check [this commit ](https://github.com/trincasidra/TrincaUI/commit/fe899d6438e64a2d68a00db915c766860cf8e686) for the actual solution (using oUF's `PostCastStart` to set the color based on `notInterruptible`). Or at least the one that worked with the mobs I was testing.
