### ISSUE TITLE
Bags stop working once opened and closed

### ISSUE THREAD

**Issue by Baine** [trincasidra/trincaui#4]
opening the bags works, but interaction with any parts of the (combined) bags isn't possible after closing it for the first time.

using commit 02e44914f0b978c06c19b05b1040493a087b26f5

when switching back to default bags it's the same behaviour for the first bag (the one with sorting button),
but interaction for bags 2-5 is working

edit: just noticed that currency/gold information is also missing
![image](https://user-images.githubusercontent.com/6566469/230714677-943c1af7-0b1b-4e2d-a45f-e29761c79f4e.png)

Edit2:
ok, now it gets weird. continued questing etc, now the bag is working just fine oo

**Comment by trincasidra** [comment]
@Baine sorry for the delay! Is this still happening with the latest update? I see I mistakenly updated the configuration for ultra-wide screen, so hopefully it was that.

In any case, and in case it still happens, let me see if I understand it; after logging in the slots from the backpack aren't responsive to clicks/drags and there's no currency? Some more questions:
- Is your character a Vulpera?
- Do you have the Authenticator set up?
- Did you log in/out while in combat or something like that?

**Comment by Baine** [comment]
don't worry, all good :)

so, what happened

logged out in an inn, logged in

opened bag (combined), all fine
close bag, open bag again
no buttons worked

closed wow, same procedure, same result

reverted bag combining, restarted client
opened bag, frames opened in the middle of the screen (in one line, next to each other), all buttons working
closed bags, opened again, buttons of main bag stopped working, other bags were still working

that stopped happening shortly after it started without any update etc.
(lightforged) draenei, authenticator.

so far it didn't happen anymore

**Comment by trincasidra** [comment]
Thanks, I've been trying but unfortunately I can't really reproduce the issue. Right now what I'm thinking would be:
- This may be related to the `styleBag` option, if the issue still happens, does changing that change the outcome?
- I see from the screenshot you do have at least an icon-related addon. It may be a taint coming up from such addon, or from the combination of that + mine. Have you tried disabling all other addons a nd see if the issue still persists? If it doesn't you may be able to rule out which addon it is, and then see if the issue happens also with TrincaUI disabled or if it only happens when both addons are enabled.

Lastly, regarding the bag frames being in one line, yes - that's expected. You can disable that by setting either `bagPosition` or `isUltraWide` to `nil` on the config. I'm thinking maybe I added the `isUltraWide`  after your last comment, so that may be irrelevant now unless  you have an ultrawide monitor.

But yeah, let me know what you find on the bags issue, hopefully we can pinpoint it before I run out of ideas 😅

**Comment by Baine** [comment]
well, I did disable all addons before opening this, but after taking the screenshot. apologies for the confusion here.

so far didn't encounter this again, so I'll close this for now.  sorry for taking your time, and thank you for your UI and time on this in general!

**Comment by trincasidra** [comment]
No worries! Thanks!
